# version: "3.8"

services:
  server1:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server1
    environment:
      - PORT=3000
      - ID=1
    networks:
      - app-network

  server2:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server2
    environment:
      - PORT=3000
      - ID=2
    networks:
      - app-network

  server3:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server3
    environment:
      - PORT=3000
      - ID=3
    networks:
      - app-network

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - server1
      - server2
      - server3

networks:
  app-network:
    driver: bridge
